### PR TITLE
Allow custom adaptation actions to be added to the actions dropdown

### PR DESCRIPTION
**Pull request by zonagit**
This is driven by need to retry processes with failed status in one of the adaptation projects.
The idea is then to add extra actions to the cws-ui dropdown menu.
KGrimes/galenatjpl can provide additional context.
Thanks

### CODE REVIEW

**Comment by galenatjpl** [comment]
General comment for @voxparcxls and @jamesfwood :  In addition to this code change, there will need to be a corresponding entry in the documentation about integration/adaptation, to mention this new extension point that adaptation customers can use.

**Comment by galenatjpl** [comment]
Thought about it some more.  Perhaps @zonagit can just add inline documentation here (directly in the codebase), instead of the core team adding docs to a wiki.  Just a thought.

**Comment by zonagit** [comment]
@galenatjpl I can do that. 
For example I can add the procedure I did for the adaptation process as a comment to the empty file
adaptation-process-actions.ftl?

**Comment by zonagit** [comment]
added doc @galenatjpl

**Review by galenatjpl — APPROVED** [review]
looks good @zonagit !

**Comment by zonagit** [comment]
Hi, would it be possible to merge this PR? I have a deadline coming up to deploy this.
Thanks!

**Review by voxparcxls — APPROVED** [review]
Good to merge.

**Comment by zonagit** [comment]
Thank you @voxparcxls.

**Pull request merged**
