### PR TITLE
Restore LoadTestIT

### PR DESCRIPTION
**Pull request by RonnyFrayRegato**
Restore the LoadTestIT by configuring the CI pipeline to handle multiple workers and updating impacted tests.

### CODE REVIEW

**Comment by RonnyFrayRegato** [comment]
Investigating test failures for CWS CI Camunda.

**Comment by RonnyFrayRegato** [comment]
The CI pipeline fails intermittently with the following error: `The hosted runner: Hosted Agent lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.`[https://github.com/NASA-AMMOS/common-workflow-service/actions/runs/3505583188](Update WebTestUtil). The ratio is about 1 in 6 runs. I recommend creating a new job that builds CWS with 2-3 workers and only runs the LoadTestIT. @jamesfwood

**Comment by RonnyFrayRegato** [comment]
The CI pipeline is now configured to handle multiple workers. The advanced-test job was added to the CWS CI Camunda workflow. The workflow jobs will send a Slack message to the development team only if a team member triggers the workflows.

**Review by jamesfwood — APPROVED** [review]
Looks great!  Thank you for the hard work on this one!  I really appreciate it!

**Pull request merged**
