### PR TITLE
IDS-9940: LDAP User Attributes Validation

### PR DESCRIPTION
**Pull request by voxparcxls**
ADDED:
* LDAP user info(givenName, sn, mail) checker. This validates the user provided LDAP account by querying for LDAP firstname, lastname, email.
* Once 3 user attributes are checked for, they are passed to the cws.properties files -  `cws/config/cws-*.properties`

---------

#### Valid LDAP user. Checked - Successful
```
checking that user provided LDAP authentication profile (UID: ldapuser) is valid...
   [OK]
```

#### Invalid LDAP user. Checked - Failed

```
checking that user provided LDAP authentication profile (UID: ldapuser) is valid...
   [WARNING]
      It was determined that your CWS Admin User ID 'ldapsuer' did not return a user first name, last name, and email.
          You must satisfy these LDAP requirements before installing CWS with CWS Admin User ID 'ldapuser'
             - Make sure your LDAP account holds the properties: givenName, sn, mail
             - Check your host machine for proper installation of LDAP Server Certificates
             - Verify the LDAP plugin bean has the correct properties
                  Plugin bean filepath: /Users/haile/dev/cws/config/templates/tomcat_conf/ldap_plugin_bean.xml
```

If the LDAP account does not have set attributes, the installer uses values in config.properties(admin_firstname, admin_lastname, admin_email) file as alternative properties settings.
```
/cws/config/work/cws-ui/cws-ui.properties
```

ex:

```
cws.admin.firstname=cwsfirstname
cws.admin.lastname=cwslastname
cws.admin.email=cwsuser@example.com
```

### CODE REVIEW

**Comment by voxparcxls** [comment]
Needed update to code:
* If Ldap values are Null, then direct the manually entered firstName, lastName, Email to .properties
`admin_firstname`, `admin_lastname`, `admin_email`

**Comment by jamesfwood** [comment]
So @voxparcxls if they don't get set, then what do the values become?  And what happens when it tries to send an email to that email?

**Comment by voxparcxls** [comment]
Logic would be:

For LDAP, CAM --
* If ldapsearch comes back empty for any of the 3 values, it would take user input(first name, last name, email) from config.properties

It will use the variable(s) `cws_user_firstname`
From here: https://github.com/NASA-AMMOS/common-workflow-service/blob/5e2cf02d903f080d6652168b90eaaaf09ac15ec6/cws-installer/src/main/java/jpl/cws/task/CwsInstaller.java#L2244


I'll put this back to draft

**Comment by voxparcxls** [comment]
Option after ERROR:
* Message saying use can set presets
* Or the user can go back and update their ldap account

**Comment by voxparcxls** [comment]
LDAP Validation Updates:

* Error message includes all missing user attributes:

```
   ERROR: LDAP Admin ID 'cwsuser' is missing attribute(s) - [givenName, sn, mail]
```


* Validation WARNING shows options to user for LDAP config fixes:
```
   POSSIBLE FIXES:
             - Option #1: (RECOMMENDED) Update your LDAP Admin account 'cwsuser' with the following
                                        LDAP attributes: givenName, sn, mail. And restart the CWS installation process.
             - Option #2: Include these 3 settings with assigned values in your configuration.properties file:
                                        - admin_firstname=[VALUE]
                                        - admin_lastname=[VALUE]
                                        - admin_email=[VALUE]
```

**Review by jamesfwood — APPROVED** [review]
Nice work!  A lot of updates here.

**Pull request merged**
